# Generated by Django 4.1.4 on 2022-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangilik',
            name='sana',
            field=models.DateField(),
        ),
    ]
